# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер чека в смене')),
                ('table_number', models.CharField(blank=True, max_length=50, verbose_name='Стол/зона')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('mixed', 'Смешанная')], default='cash', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит')),
                ('deposit_method', models.CharField(blank=True, default='', max_length=20, verbose_name='Способ депозита')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.order')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='shifts.shift')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'orders_receipt',
                'ordering': ['-issued_at'],
                'unique_together': {('shift', 'number')},
            },
        ),
    ]
