# Generated by Django 5.1.4 on 2026-06-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Возврат депозита'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит (списано)'),
        ),
    ]
