# Generated by Django 5.1.4 on 2026-06-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_refund_amount_alter_receipt_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='deposit_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='', max_length=20, verbose_name='Способ депозита'),
        ),
    ]
