# Generated by Django 5.1.4 on 2026-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. депозит, ₽'),
        ),
        migrations.AddField(
            model_name='zone',
            name='requires_deposit',
            field=models.BooleanField(default=False, verbose_name='VIP-зона (берётся депозит)'),
        ),
    ]
