# Generated by Django 5.1.4 on 2026-06-12 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.TextField(blank=True, verbose_name='Строка QR-кода')),
                ('hash', models.CharField(blank=True, max_length=64, verbose_name='Hash в сервисе проверки')),
                ('status', models.CharField(choices=[('wait', 'В очереди'), ('process', 'Проверяется'), ('done', 'Готов к оприходованию'), ('error', 'Ошибка'), ('applied', 'Оприходован')], default='wait', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('store', models.CharField(blank=True, max_length=200, verbose_name='Магазин')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchased_at', models.CharField(blank=True, max_length=30, verbose_name='Дата чека')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Состав чека')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_imports', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Импорт чека',
                'verbose_name_plural': 'Импорты чеков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_name', models.CharField(max_length=300, unique=True, verbose_name='Название в чеке')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_mappings', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Сопоставление чека',
                'verbose_name_plural': 'Сопоставления чеков',
            },
        ),
    ]
