# Generated by Django 5.1.4 on 2026-06-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Магазин'),
        ),
    ]
