# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('station', models.CharField(blank=True, choices=[('', 'Любые чеки'), ('bar', 'Бар'), ('waiter', 'Официанты')], default='', help_text='Чьи чеки печатает: бара, официантов или любые', max_length=20, verbose_name='Назначение')),
                ('connection', models.CharField(choices=[('network', 'Ethernet (raw, порт 9100)'), ('agent', 'USB через локальный агент')], default='network', max_length=20)),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='IP/хост (для Ethernet)')),
                ('port', models.PositiveIntegerField(default=9100)),
                ('agent_key', models.CharField(blank=True, max_length=64, verbose_name='Ключ агента (для USB)')),
                ('width', models.PositiveSmallIntegerField(default=48, verbose_name='Ширина, символов')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'orders_printer',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BAR DREAM', max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='vk.com/mydreambar', max_length=100, verbose_name='Подзаголовок (адрес, соцсети)')),
                ('footer', models.CharField(blank=True, default='Спасибо за визит!', max_length=100, verbose_name='Текст внизу чека')),
                ('qr_data', models.CharField(blank=True, default='', help_text='Пусто — QR не печатается', max_length=200, verbose_name='QR-код (ссылка или текст)')),
                ('qr_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Подпись под QR-кодом')),
                ('print_second_copy', models.BooleanField(default=True, verbose_name='Печатать копию «для сверки»')),
            ],
            options={
                'verbose_name': 'Настройки чека',
                'verbose_name_plural': 'Настройки чека',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Чек'), ('report', 'Отчёт')], default='receipt', max_length=20)),
                ('payload', models.BinaryField(verbose_name='ESC/POS-данные')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('printing', 'Печатается'), ('done', 'Напечатано'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Забрано агентом')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='printers.printer')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='receipts.receipt')),
            ],
            options={
                'verbose_name': 'Задание печати',
                'verbose_name_plural': 'Задания печати',
                'db_table': 'orders_printjob',
                'ordering': ['created_at'],
            },
        ),
    ]
