# Generated by Django 5.1.4 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='station',
            field=models.CharField(blank=True, choices=[('', 'Любые чеки'), ('bar', 'Бар'), ('waiter', 'Официанты')], default='', help_text='Чьи чеки печатает: бара, официантов или любые', max_length=20, verbose_name='Назначение'),
        ),
    ]
