# Generated by Django 5.1.4 on 2026-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_printer_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BAR DREAM', max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, default='vk.com/mydreambar', max_length=100, verbose_name='Подзаголовок (адрес, соцсети)')),
                ('footer', models.CharField(blank=True, default='Спасибо за визит!', max_length=100, verbose_name='Текст внизу чека')),
                ('print_second_copy', models.BooleanField(default=True, verbose_name='Печатать копию «для сверки»')),
            ],
            options={
                'verbose_name': 'Настройки чека',
                'verbose_name_plural': 'Настройки чека',
            },
        ),
    ]
