# Generated by Django 5.1.4 on 2026-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_receiptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='qr_data',
            field=models.CharField(blank=True, default='', help_text='Пусто — QR не печатается', max_length=200, verbose_name='QR-код (ссылка или текст)'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='qr_label',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Подпись под QR-кодом'),
        ),
    ]
