# Generated by Django 5.1.4 on 2026-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_receiptsettings_qr_data_receiptsettings_qr_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Забрано агентом'),
        ),
    ]
