# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('waiter', 'Официант'), ('bartender', 'Бармен'), ('kitchen', 'Кухня'), ('wardrobe', 'Гардероб')], default='waiter', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('allowed_roles', models.JSONField(blank=True, default=list, verbose_name='Доступные роли')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='PIN (хэш)')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Сменить пароль при входе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
                'db_table': 'orders_userprofile',
            },
        ),
    ]
