# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.modifier'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modifiers', to='orders.orderitem'),
        ),
    ]
