# Generated by Django 5.1.4 on 2026-06-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объём/вес'),
        ),
    ]
