# Generated by Django 5.1.4 on 2026-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderglassware'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_names',
            field=models.JSONField(blank=True, default=dict, verbose_name='Имена гостей'),
        ),
    ]
