# Generated by Django 5.1.4 on 2026-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_status',
            field=models.CharField(choices=[('new', 'Новый'), ('cooking', 'Готовится'), ('ready', 'Готов')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('waiter', 'Официант'), ('bartender', 'Бармен'), ('kitchen', 'Кухня'), ('wardrobe', 'Гардероб')], default='waiter', max_length=20),
        ),
    ]
