# Generated by Django 5.1.4 on 2026-06-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_kitchen_status_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guests',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Гостей'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер чека в смене')),
                ('table_number', models.CharField(blank=True, max_length=10, verbose_name='Стол/зона')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('mixed', 'Смешанная')], default='cash', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.order')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.shift')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['-issued_at'],
                'unique_together': {('shift', 'number')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.receipt'),
        ),
    ]
