# Generated by Django 5.1.4 on 2026-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_sent',
            field=models.BooleanField(default=True, verbose_name='Отправлен на кухню/бар'),
        ),
    ]
