# Generated by Django 5.1.4 on 2026-06-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (снимок)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объём (снимок)'),
        ),
    ]
