# Generated by Django 5.1.4 on 2026-06-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_guest_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('connection', models.CharField(choices=[('network', 'Ethernet (raw, порт 9100)'), ('agent', 'USB через локальный агент')], default='network', max_length=20)),
                ('host', models.CharField(blank=True, max_length=100, verbose_name='IP/хост (для Ethernet)')),
                ('port', models.PositiveIntegerField(default=9100)),
                ('agent_key', models.CharField(blank=True, max_length=64, verbose_name='Ключ агента (для USB)')),
                ('width', models.PositiveSmallIntegerField(default=48, verbose_name='Ширина, символов')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Чек')], default='receipt', max_length=20)),
                ('payload', models.BinaryField(verbose_name='ESC/POS-данные')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('printing', 'Печатается'), ('done', 'Напечатано'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='orders.printer')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='orders.receipt')),
            ],
            options={
                'verbose_name': 'Задание печати',
                'verbose_name_plural': 'Задания печати',
                'ordering': ['created_at'],
            },
        ),
    ]
