# Generated by Django 5.1.4 on 2026-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_printer_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Доступные роли'),
        ),
    ]
