# Generated by Django 5.1.4 on 2026-06-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_userprofile_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='print_station',
            field=models.CharField(blank=True, choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], default='', help_text='Переопределяет категорию. Оставьте пустым — будет использоваться тип категории.', max_length=20, verbose_name='Станция приготовления'),
        ),
    ]
