# Generated by Django 5.1.4 on 2026-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_backfill_orderitem_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит стола'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='', max_length=20, verbose_name='Способ внесения депозита'),
        ),
    ]
