# Generated by Django 5.1.4 on 2026-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_print_station_to_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Закончилось'),
        ),
    ]
