# Generated by Django 5.1.4 on 2026-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_deposit_amount_order_deposit_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено'),
        ),
    ]
