# Generated by Django 5.1.4 on 2026-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ключ идемпотентности',
                'verbose_name_plural': 'Ключи идемпотентности',
                'db_table': 'audit_idempotencykey',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_idemp_created_681fce_idx')],
            },
        ),
    ]
