# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активное')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('print_station', models.CharField(blank=True, choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], default='', help_text='Оставьте пустым — будет использоваться принтер раздела.', max_length=20, verbose_name='Принтер (переопределение)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'db_table': 'orders_menucategory',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('max_selections', models.PositiveIntegerField(default=1, verbose_name='Макс. выборов (0=без лимита)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Группа модификаторов',
                'verbose_name_plural': 'Группы модификаторов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Объём/вес')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость')),
                ('is_active', models.BooleanField(default=True)),
                ('is_out_of_stock', models.BooleanField(default=False, verbose_name='Закончилось')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('print_station', models.CharField(blank=True, choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], default='', help_text='Переопределяет категорию. Оставьте пустым — будет использоваться категория.', max_length=20, verbose_name='Принтер (переопределение)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'db_table': 'orders_menuitem',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('station_type', models.CharField(choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], max_length=20, verbose_name='Станция')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='menu.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Раздел меню',
                'verbose_name_plural': 'Разделы меню',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menusection'),
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доп. цена (₽)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'Модификатор',
                'verbose_name_plural': 'Модификаторы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menu.menuitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'Модификатор позиции',
                'verbose_name_plural': 'Модификаторы позиций',
                'ordering': ['sort_order'],
                'unique_together': {('menu_item', 'modifier_group')},
            },
        ),
    ]
