# Generated by Django 5.1.4 on 2026-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_finalize_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='print_station',
            field=models.CharField(blank=True, choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], default='', help_text='Оставьте пустым — будет использоваться принтер раздела.', max_length=20, verbose_name='Принтер (переопределение)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='print_station',
            field=models.CharField(blank=True, choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('hookah', 'Кальян')], default='', help_text='Переопределяет категорию. Оставьте пустым — будет использоваться категория.', max_length=20, verbose_name='Принтер (переопределение)'),
        ),
    ]