# Generated by Django 5.1.4 on 2026-06-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracelet_number', models.CharField(max_length=30, verbose_name='№ браслета')),
                ('price', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tickets', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Входной билет',
                'verbose_name_plural': 'Входные билеты',
                'db_table': 'orders_entryticket',
                'ordering': ['bracelet_number'],
            },
        ),
    ]
